clear, clc;

fprintf('Microscopy pipeline for a single dataset...\n\n');

% add the software to the path
addpath(genpath('/cm/shared/apps_local/petakit5d/'));

% data path
dataPath = '/mmfs2/scratch/SDSMT.LOCAL/bscott/DataUpload/20260402_py_FLM_2XFyve_mSca_mem_NG/20260402_py_FLM_2XFyve_mSca_mem_NG/cell/cell_MMStack_Pos0/CROP/';

% general parameters.
xyPixelSize = 0.136;
dz = 0.3;
Reverse = true;
ChannelPatterns = {'C00_T000', 'C01_T000', 'C02_T000', 'C03_T000'};
Save16bit = true;
Overwrite = true;
Streaming = false;
parseCluster = false;
cpusPerTask = 24;
configFile = '';
mccMode = false;

Deskew = true;
Rotate = true;
Stitch = false;

DSRCombined = true;

FFCorrection = false;
LowerLimit = 0.4;
constOffset = 1;
FFImagePaths = {'', '', '', ''};
BackgroundPaths = {'', '', '', ''};

ImageListFullpaths = '';
axisOrder = '-x,y,z';

minModifyTime = 1;
maxModifyTime = 10;
maxWaitLoopNum = 10;

% We must pass inputAxisOrder='xyz' if the CROP images were generated by opym with rotate_90=True.
% If they were NOT rotated, 'yxz' (PetaKit default) is correct.
% I will explicitly pass the default parameter so you can see it.
inputAxisOrder = 'yxz';
outputAxisOrder = 'yxz';

XR_microscopeAutomaticProcessing(dataPath, 'xyPixelSize', xyPixelSize, 'dz', dz,  ...
    'Reverse', Reverse, 'ChannelPatterns', ChannelPatterns, 'Save16bit', Save16bit, ...
    'Overwrite', Overwrite, 'Streaming', Streaming, 'Deskew', Deskew, 'Rotate', Rotate, ...
    'Stitch', Stitch, 'ImageListFullpaths', ImageListFullpaths, 'axisOrder', axisOrder, ...
    'FFCorrection', FFCorrection, 'LowerLimit', LowerLimit, 'constOffset', constOffset, ...
    'FFImagePaths', FFImagePaths, 'BackgroundPaths', BackgroundPaths,'minModifyTime', minModifyTime, ...
    'maxModifyTime', maxModifyTime, 'maxWaitLoopNum', maxWaitLoopNum, 'parseCluster', parseCluster, ...
    'cpusPerTask', cpusPerTask, 'configFile', configFile, 'mccMode', mccMode, ...
    'inputAxisOrder', inputAxisOrder, 'outputAxisOrder', outputAxisOrder);
